1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code and functions that can be imported and used in your Python programs. These libraries provide various functionalities, such as mathematical operations, data manipulation, web development, machine learning, and much more.

We use Python libraries for several reasons:

1. **Code Reusability**: Libraries contain pre-written code that can be reused in multiple projects, saving time and effort.

2. **Efficiency**: Libraries often contain optimized code, making them more efficient than writing your own functions from scratch.

3. **Functionality**: Libraries extend the capabilities of Python by providing specialized functions and tools for specific tasks, such as data analysis, image processing, or web scraping.

4. **Community Support**: Many Python libraries are open source and have active communities of developers who contribute updates, bug fixes, and new features, providing valuable support to users.

5. **Standardization**: By using widely adopted libraries, you can adhere to industry standards and best practices, improving the maintainability and compatibility of your code.

Overall, Python libraries empower developers to build complex applications more quickly and efficiently by leveraging existing solutions and expertise from the broader Python community.

2. What is the difference between Numpy array and List?

NumPy arrays and Python lists are both used to store collections of data, but they have several differences in terms of functionality, performance, and usage:

1. **Performance**: NumPy arrays are more efficient in terms of memory usage and computation speed compared to Python lists, especially for large datasets. This is because NumPy arrays are implemented in C and optimized for performance, whereas Python lists are dynamic arrays that store references to objects.

2. **Data Types**: NumPy arrays can only store elements of the same data type, which leads to more efficient storage and operations. In contrast, Python lists can store elements of different data types within the same list.

3. **Functionality**: NumPy arrays support a wide range of mathematical operations and array manipulations, such as element-wise operations, matrix operations, slicing, reshaping, and broadcasting. Python lists have fewer built-in functions and are generally less optimized for numerical computations.

4. **Memory Management**: NumPy arrays have a fixed size upon creation, which makes memory management more efficient compared to Python lists, which can dynamically resize themselves as elements are added or removed.

5. **Ease of Use**: Python lists are more flexible and easier to work with for general-purpose tasks, as they support a wider range of operations and can store heterogeneous data types. NumPy arrays are more specialized and optimized for numerical computing tasks.

In summary, NumPy arrays are preferred for numerical computations and scientific computing tasks due to their efficiency and specialized functionality, while Python lists are more versatile and suitable for general-purpose programming tasks.

3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [50]:
import numpy as np
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Array Shape - ",arr.shape)
print("Array Size - ",arr.size)
print("Array Dimension - ",arr.ndim)

Array Shape -  (3, 4)
Array Size -  12
Array Dimension -  2


4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [51]:
import numpy as np
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr)
print("Array's first row - ",arr[[0]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array's first row -  [[1 2 3 4]]


5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [53]:
import numpy as np
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr[3-1,4-1]

12

6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [54]:
import numpy as np
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr[1::2, 1::2]

array([[6, 8]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [55]:
import numpy as np
np.random.rand(3,3)

array([[0.19306547, 0.8573183 , 0.73753131],
       [0.04168346, 0.06353767, 0.90778072],
       [0.55451782, 0.44278432, 0.77823233]])

8. Describe the difference between np.random.rand and np.random.randn?

`np.random.rand` and `np.random.randn` are both functions in NumPy's random module used to generate random numbers, but they have differences in how they generate these numbers and the distributions they sample from:

1. **np.random.rand**:
   - This function generates random numbers from a uniform distribution over the half-open interval [0, 1). It takes the shape of the output array as input and returns an array of random numbers with that shape.
   - The numbers generated by `np.random.rand` are uniformly distributed between 0 and 1, meaning each value has an equal probability of being selected.
   - Syntax: `np.random.rand(d0, d1, ..., dn)`
   - Example: `np.random.rand(3, 3)` generates a 3x3 array of random numbers between 0 and 1.

2. **np.random.randn**:
   - This function generates random numbers from a standard normal distribution (also known as Gaussian distribution) with mean 0 and standard deviation 1. It takes the shape of the output array as input and returns an array of random numbers with that shape.
   - The numbers generated by `np.random.randn` are not uniformly distributed; instead, they follow a bell-shaped curve centered around 0, with most values clustering near the mean and fewer values occurring further away.
   - Syntax: `np.random.randn(d0, d1, ..., dn)`
   - Example: `np.random.randn(3, 3)` generates a 3x3 array of random numbers from a standard normal distribution.

In summary, `np.random.rand` generates random numbers from a uniform distribution over the interval [0, 1), while `np.random.randn` generates random numbers from a standard normal distribution with mean 0 and standard deviation 1. The choice between these functions depends on the specific distribution of random numbers needed for a particular application.

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [56]:
import numpy as np
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr)
print("Present dimension - ",arr.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Present dimension -  2


In [57]:
print(np.expand_dims(arr,0))
#increasing row dimension
print("Dimension increased to - ",(np.expand_dims(arr,0)).ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Dimension increased to -  3


In [58]:
print(np.expand_dims(arr,1))
#increasing column dimension
print("Dimension increased to - ",(np.expand_dims(arr,1)).ndim)

[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
Dimension increased to -  3


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [59]:
import numpy as np
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Original array - \n",arr)
print("Transposed array - \n",arr.T)

Original array - 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transposed array - 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:
Matrix A : [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B : [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python:
Index wise multiplication
Matrix multiplication
Add both the matrix
Subtact matix B from A
Divide Matix B by A

In [60]:
import numpy as np
A=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
B=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [61]:
#Index wise multiplication
A*5

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [62]:
#matrix multiplication
A@B
# A - 3x4
# B - 3x4
#as number of columns in A matrix is not equal to number of rows in B matrix
#matrix multiplication is not possible
#A@B and B@A both are not possible

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [63]:
#Add both the matrix
A+B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [64]:
#Subtact matix B from A
B-A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [65]:
#Divide Matix B by A
B/A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12. Which function in Numpy can be used to swap the byte order of an array?

In [66]:
import numpy as np
arr = np.array([1, 2, 3, 4])
swapped_arr = arr.byteswap()
print("Original array:", arr)
print("Swapped array:", swapped_arr)

Original array: [1 2 3 4]
Swapped array: [ 72057594037927936 144115188075855872 216172782113783808
 288230376151711744]


13. What is the significance of the np.linalg.inv function?

The `np.linalg.inv` function in NumPy is used to compute the multiplicative inverse of a square matrix. In linear algebra, the multiplicative inverse (or matrix inverse) of a square matrix \( A \) is another matrix \( A^{-1} \) such that their product is the identity matrix \( I \), i.e., \( A \times A^{-1} = A^{-1} \times A = I \).

The significance of `np.linalg.inv` lies in its applications in solving systems of linear equations and in various numerical methods in science and engineering. Some key applications include:

1. **Solving Systems of Linear Equations**: Given a system of linear equations represented in matrix form \( Ax = b \), where \( A \) is the coefficient matrix, \( x \) is the vector of unknowns, and \( b \) is the right-hand side vector, you can solve for \( x \) by computing \( x = A^{-1}b \).

2. **Least Squares Regression**: In linear regression analysis, when the ordinary least squares (OLS) method is used to fit a linear model to data, the coefficients can be computed using the matrix formula \( \beta = (X^T X)^{-1} X^T y \), where \( X \) is the design matrix, \( y \) is the response vector, and \( \beta \) is the vector of coefficients. Here, \( (X^T X)^{-1} \) is computed using `np.linalg.inv`.

3. **Eigenvalue Problems**: The inverse of a matrix plays a crucial role in computing eigenvalues and eigenvectors. For example, the eigenvalues of a matrix \( A \) are the roots of the characteristic polynomial \( \det(A - \lambda I) = 0 \), and the eigenvectors corresponding to these eigenvalues can be computed using the formula \( (A - \lambda I)^{-1} \), where \( I \) is the identity matrix.

4. **Numerical Stability**: In numerical computations, the condition number of a matrix \( A \) provides a measure of how sensitive the solution is to changes in the input. When solving linear systems or computing matrix inverses, a high condition number can lead to numerical instability. `np.linalg.inv` can be used to assess the condition number and handle numerical stability issues.

In summary, `np.linalg.inv` is a fundamental function in NumPy for computing the inverse of a matrix, and it has wide-ranging applications in various fields of science, engineering, and data analysis.

14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to rearrange the elements of an array into a new shape while preserving the same data.

In [67]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (3, 2))
print("Original array:")
print(arr)
print("Reshaped array:")
print(reshaped_arr)

Original array:
[1 2 3 4 5 6]
Reshaped array:
[[1 2]
 [3 4]
 [5 6]]


15. What is broadcasting in Numpy?

Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be combined in arithmetic operations. It enables NumPy to perform element-wise operations between arrays with different shapes without explicitly creating multiple copies of the data. This makes operations more memory-efficient and allows for more concise and readable code.

The basic idea behind broadcasting is to extend smaller arrays so that they have compatible shapes for arithmetic operations with larger arrays. Two arrays are compatible for broadcasting if their shapes are either equal or if one of them has a dimension of size 1. NumPy then automatically broadcasts the smaller array across the larger one to perform the operation.

Here are the key rules of broadcasting in NumPy:

1. **Dimensions Compatibility**: Arrays must have the same number of dimensions. If they have different numbers of dimensions, the shape of the smaller array is padded with ones on its left side until the numbers of dimensions match.

2. **Size Compatibility**: The sizes of the corresponding dimensions must either be the same or one of them must be 1. If the sizes are not the same, NumPy will "stretch" the array with size 1 along that dimension to match the size of the other array.

3. **Broadcasting Iteration**: After extending the arrays to have compatible shapes, NumPy performs element-wise operations by iterating over the dimensions. When an array has size 1 along a dimension, its values are effectively "broadcast" along that dimension during the operation.

Broadcasting simplifies many common tasks in NumPy, such as adding a constant to every element of an array or multiplying two arrays with different shapes. It's a fundamental concept that underlies many of the operations in NumPy and contributes to its efficiency and versatility.